proxies:
- name: "🚩 中国直连"
  type: direct
  udp: true

pr:
  type: select
  proxies: &1
  - "💥 手动选择"
  - "♻️ 自动选择"
  - "🏅 香港自动"
  - "🥇 美国自动"
  - "🥈 台湾自动"
  - "🥉 新加坡自动"
  - "🔞 日本自动"
  - "🫧 韩国自动"
  - "🚧 香港故转"
  - "🚧 美国故转"
  - "🚧 日本故转"
  - "🇭🇰 香港节点"
  - "🇺🇲 美国节点"
  - "🇹🇼 台湾节点"
  - "🇸🇬 新加坡节点"
  - "🇯🇵 日本节点"
  - "🇰🇷 韩国节点"
  - "🇨🇦 加拿大节点"
  - "🚦 IPV6自动"
  - "🚥 IPV6节点"
  - "💯 全部节点"
  - "🪧 其他节点"
  - "🚩 中国直连"
proxy-groups:
- name: "💥 手动选择"
  type: select
  proxies:
  - "♻️ 自动选择"
  - "🏅 香港自动"
  - "🥇 美国自动"
  - "🥈 台湾自动"
  - "🥉 新加坡自动"
  - "🔞 日本自动"
  - "🫧 韩国自动"
  - "🚧 香港故转"
  - "🚧 美国故转"
  - "🚧 日本故转"
  - "🇭🇰 香港节点"
  - "🇺🇲 美国节点"
  - "🇹🇼 台湾节点"
  - "🇸🇬 新加坡节点"
  - "🇯🇵 日本节点"
  - "🇰🇷 韩国节点"
  - "🇨🇦 加拿大节点"
  - "🚦 IPV6自动"
  - "🚥 IPV6节点"
  - "💯 全部节点"
  - "🪧 其他节点"
  - "🚩 中国直连"
- name: "📹 YouTube"
  type: select
  proxies: *1
- name: "🪁 GoogleFCM"
  type: select
  proxies: *1
- name: "👑 Google"
  type: select
  proxies: *1
- name: "✨️ ChatGPT"
  type: select
  proxies: *1
- name: "🎉 Gemini"
  type: select
  proxies: *1
- name: "🐈‍⬛ GitHub"
  type: select
  proxies: *1
- name: "🎨 Pixiv"
  type: select
  proxies: *1
- name: "🖥️️ Microsoft"
  type: select
  proxies: *1
- name: "📱 TikTok"
  type: select
  proxies: *1
- name: "💚 Whatsapp"
  type: select
  proxies: *1
- name: "🪞 Instagram"
  type: select
  proxies: *1
- name: "🎭 Facebook"
  type: select
  proxies: *1
- name: "🐦 Twitter"
  type: select
  proxies: *1
- name: "📠 Telegram"
  type: select
  proxies: *1
- name: "🎬 NETFLIX"
  type: select
  proxies: *1
- name: "🎶 Spotify"
  type: select
  proxies: *1
- name: "🎮 Steam"
  type: select
  proxies: *1
- name: "💵️ PayPal"
  type: select
  proxies: *1
- name: "🍎 Apple"
  type: select
  proxies:
  - "🚩 中国直连"
  - "💥 手动选择"
- name: "㊙️ 全球直连"
  type: select
  proxies:
  - "🚩 中国直连"
  - "💥 手动选择"
- name: "🥅 漏网之鱼"
  type: select
  proxies: *1
- name: "🇭🇰 香港节点"
  type: select
  include-all: true
  filter: "(?i)港|hk|hongkong|hong kong"
- name: "🇹🇼 台湾节点"
  type: select
  include-all: true
  filter: "(?i)台|tw|taiwan"
- name: "🇯🇵 日本节点"
  type: select
  include-all: true
  filter: "(?i)日本|jp|japan"
- name: "🇺🇲 美国节点"
  type: select
  include-all: true
  filter: "(?i)美|us|unitedstates|united states"
- name: "🇸🇬 新加坡节点"
  type: select
  include-all: true
  filter: "(?i)新加坡|sg|singapore"
- name: "🇰🇷 韩国节点"
  type: select
  include-all: true
  filter: "(?i)韩国|kr|korea"
- name: "🇨🇦 加拿大节点"
  type: select
  include-all: true
  filter: "(?=.*(加|ca|canada))^((?!(台|日|韩|深|新|美|)).)*$"
- name: "🚥 IPV6节点"
  type: select
  include-all: true
  filter: "(?i)IPV6|ipv6"
- name: "🪧 其他节点"
  type: select
  include-all: true
  filter: "^((?!(直连|官网|剩余|到期|异常|失败|香港|台湾|日本|韩国|新加坡|加拿大|深|美国)).)*$"
- name: "🚧 香港故转"
  type: fallback
  include-all: true
  tolerance: 20
  interval: 180
  filter: "(?=.*(港|HK|(?i)Hongkong|Hong kong))^((?!(台|日|韩|新|深|美)).)*$"
- name: "🚧 台湾故转"
  type: fallback
  include-all: true
  tolerance: 20
  interval: 180
  filter: "(?=.*(台|TW|(?i)Taiwan))^((?!(港|日|韩|新|深|美)).)*$"
- name: "🚧 美国故转"
  type: fallback
  include-all: true
  tolerance: 20
  interval: 180
  filter: "(?=.*(美|US|(?i)States|America))^((?!(港|台|日|韩|新)).)*$"
- name: "🚧 日本故转"
  type: fallback
  include-all: true
  tolerance: 20
  interval: 180
  filter: "(?=.*(日|JP|(?i)Japan))^((?!(港|台|韩|新|美|尼)).)*$"
- name: "♻️ 自动选择"
  type: url-test
  include-all: true
  tolerance: 100
  interval: 180
  filter: "^((?!(直连|官网|剩余|到期|异常|失败)).)*$"
- name: "🏅 香港自动"
  type: url-test
  include-all: true
  tolerance: 100
  interval: 180
  filter: "(?=.*(港|HK|(?i)Hongkong|Hong kong))^((?!(台|日|韩|新|深|美)).)*$"
- name: "🥈 台湾自动"
  type: url-test
  include-all: true
  tolerance: 100
  interval: 180
  filter: "(?=.*(台|TW|(?i)Taiwan))^((?!(港|日|韩|新|深|美)).)*$"
- name: "🔞 日本自动"
  type: url-test
  include-all: true
  tolerance: 100
  interval: 180
  filter: "(?=.*(日|JP|(?i)Japan))^((?!(港|台|韩|新|美|尼)).)*$"
- name: "🥇 美国自动"
  type: url-test
  include-all: true
  tolerance: 100
  interval: 180
  filter: "(?=.*(美|US|(?i)States|America))^((?!(港|台|日|韩|新)).)*$"
- name: "🫧 韩国自动"
  type: url-test
  include-all: true
  tolerance: 100
  interval: 180
  filter: "(?=.*(韩|KR|(?i)Korea))^((?!(台|日|新|深|美)).)*$"
- name: "🥉 新加坡自动"
  type: url-test
  include-all: true
  tolerance: 100
  interval: 180
  filter: "(?=.*((?i)新加坡|Sg|singapore))^((?!(台|日|韩|深|美)).)*$"
- name: "🚦 IPV6自动"
  type: select
  include-all: true
  tolerance: 20
  interval: 300
  filter: "(?i)IPV6|ipv6"
- name: "💯 全部节点"
  type: select
  include-all: true
  filter: "^((?!(直连|官网|剩余|到期|异常|失败)).)*$"
rules:
- "RULE-SET,private_domain,🚩 中国直连"
- "RULE-SET,direct,🚩 中国直连"
- "RULE-SET,apple_domain,🍎 Apple"
- "RULE-SET,proxy,💥 手动选择"
- "RULE-SET,ai,✨️ ChatGPT"
- "RULE-SET,gemini_domain,🎉 Gemini"
- "RULE-SET,github_domain,🐈‍⬛ GitHub"
- "RULE-SET,pixiv_domain,🎨 Pixiv"
- "RULE-SET,youtube_domain,📹 YouTube"
- "RULE-SET,googlefcm_domain,🪁 GoogleFCM"
- "RULE-SET,google_domain,👑 Google"
- "RULE-SET,microsoft_domain,🖥️️ Microsoft"
- "RULE-SET,tiktok_domain,📱 TikTok"
- "RULE-SET,whatsapp_domain,💚 Whatsapp"
- "RULE-SET,instagram_domain,🪞 Instagram"
- "RULE-SET,facebook_domain,🎭 Facebook"
- "RULE-SET,twitter_domain,🐦 Twitter"
- "RULE-SET,telegram_domain,📠 Telegram"
- "RULE-SET,netflix_domain,🎬 NETFLIX"
- "RULE-SET,spotify_domain,🎶 Spotify"
- "RULE-SET,steam_domain,🎮 Steam"
- "RULE-SET,paypal_domain,💵️ PayPal"
- "RULE-SET,geolocation-!cn,💥 手动选择"
- "RULE-SET,cn_domain,㊙️ 全球直连"
- "RULE-SET,google_ip,👑 Google,no-resolve"
- "RULE-SET,netflix_ip,🎬 NETFLIX,no-resolve"
- "RULE-SET,whatsapp_ip,💚 Whatsapp,no-resolve"
- "RULE-SET,instagram_ip,🪞 Instagram,no-resolve"
- "RULE-SET,facebook.ip,🎭 Facebook,no-resolve"
- "RULE-SET,twitter_ip,🐦 Twitter,no-resolve"
- "RULE-SET,telegram_ip,📠 Telegram,no-resolve"
- "RULE-SET,cn_ip,㊙️ 全球直连"
- "MATCH,🥅 漏网之鱼"
rule-anchor:
  ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
  domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
  soxmoox:
    type: http
    interval: 86400
    behavior: domain
    format: text
  class:
    type: http
    interval: 86400
    behavior: classical
    format: text
rule-providers:
  private_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs
  direct:
    type: http
    interval: 86400
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/SoxMoox/Open-clash/refs/heads/main/Direct.list
  proxy:
    type: http
    interval: 86400
    behavior: classical
    format: text
    url: https://raw.githubusercontent.com/SoxMoox/Open-clash/refs/heads/main/ProxyLite.list
  ai:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-ai-chat-!cn.mrs
  gemini_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/gemini.mrs
  youtube_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs
  googlefcm_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/googlefcm.mrs
  google_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs
  github_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs
  pixiv_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/pixiv.mrs
  whatsapp_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/whatsapp.mrs
  instagram_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/instagram.mrs
  facebook_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/facebook.mrs
  twitter_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/x.mrs
  telegram_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs
  netflix_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs
  spotify_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/spotify.mrs
  steam_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/steam.mrs
  paypal_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs
  microsoft_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs
  apple_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple-cn.mrs
  tiktok_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs
  gfw_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/gfw.mrs
  geolocation-!cn:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs
  cn_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs
  cn_ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs
  google_ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs
  gemini_ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/gemini.mrs
  whatsapp_ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/whatsapp.mrs
  instagram_ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs
  facebook.ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/facebook.mrs
  twitter_ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/x.mrs
  telegram_ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs
  netflix_ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs

